name: update test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'run'
        required: true
        default: 'false'
  
  schedule:
    - cron: 0 19 * * *
  
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: updatefile
      run: |
        touch cnv4.txt
        if [[ `cat cnv4.txt |wc -l` -eq 0 ]];then
          echo "null"
        else
          rm -rf cnipv4.list
          awk '{print "IP-CIDR,"$0}' cnv4.txt > cnipv4.list
          rm -rf cnv4.txt
        fi

        touch cnv6.txt
        if [[ `cat cnv6.txt |wc -l` -eq 0 ]];then
          echo "null"
        else
          rm -rf cnipv6.list
          awk '{print "IP-CIDR6,"$0}' cnv6.txt > cnipv6.list
          rm -rf cnv6.txt
        fi

        
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.4.0
      with:
        add: "-A"
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}     
